name: Build and Deploy iOS App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app

    - name: Install provisioning profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/MyApp.mobileprovision

    - name: Set up signing certificate
      run: |
        echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > cert.p12
        security create-keychain -p "temp1234" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "temp1234" build.keychain
        security import cert.p12 -k build.keychain -P "${{ secrets.CERT_PASSWORD }}" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple: -s -k "temp1234" build.keychain

    - name: Debug: List files
      run: ls -la

    - name: Build app
      run: |
        xcodebuild \
          -project MyApp.xcodeproj \
          -scheme MyApp \
          -configuration Release \
          -archivePath $PWD/build/MyApp.xcarchive \
          archive \
          CODE_SIGN_STYLE=Manual \
          PROVISIONING_PROFILE_SPECIFIER="MyProvisioningProfile"

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath $PWD/build/MyApp.xcarchive \
          -exportPath $PWD/build \
          -exportOptionsPlist ExportOptions.plist

    - name: Upload to App Store
      run: |
        xcrun altool --upload-app -f build/MyApp.ipa \
          --type ios \
          --username "${{ secrets.APPSTORE_USERNAME }}" \
          --password "${{ secrets.APPSTORE_APP_PASSWORD }}"
